application: {{ cookiecutter.repo_name }}
version: 1
runtime: python27
api_version: 1
threadsafe: yes

includes:
- {{ cookiecutter.repo_name }}/include.yaml

libraries:
- name: webapp2
  version: latest

